import { Button } from "@mantine/core";
import { notifications } from "@mantine/notifications";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button onClick={() => notifications.show({ message: "Teste" })}>
        Notification
      </Button>
    </>
  );
}
