"use client";
import { Content } from "@/@Types/Page";
import { Carro } from "@/@Types/Carro";
import React from "react";
import CardCarro from "./Card";
import { Pagination, SimpleGrid } from "@mantine/core";
import Head from "next/head";

const Page = () => {
  const [page, setPage] = React.useState(1);
  const [totalPages, setTotalPages] = React.useState(0);

  const [data, setData] = React.useState<Content<Carro>>();
  const content = React.useMemo(() => data?.content, [data]);

  React.useEffect(() => {
    getInitialProps<Carro>(page - 1).then((data) => {
      setTotalPages(data.totalPages);
      setData(data);
    });
    return () => {};
  }, [page]);
  return (
    <div>
      <Head>
        <title>Carros | Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Carros</h1>
      <Pagination
        total={totalPages}
        siblings={3}
        value={page}
        onChange={setPage}
      />
      <SimpleGrid cols={4} p={"md"}>
        {content?.map((carro) => (
          <CardCarro key={carro.id} {...carro} />
        ))}
      </SimpleGrid>
    </div>
  );
};

async function getInitialProps<T>(page: number) {
  const res = await fetch("http://localhost:8080/cars?page=" + page, {
    next: { revalidate: 1 },
  });

  if (!res.ok) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error("Failed to fetch data");
  }
  return res.json() as Promise<Content<T>>;
}

export default Page;
